Fix git enhancement #234, adding an hyperlink to an image
mathieumack/OpenXMLSDK.Engine pull request #235
Opened 2021-12-14 10:31 UTC by TataneCode

This evolution allow to configure an hyperlink for an image.

2021-12-14 11:13 UTC, mathieumack commented
As said in the original issue (#234), it's better to update the hyperlink object in order to be able to apply hyperlink on many objects instead only Image.
Please update the Hyperlink object instead Image object.
The goal is to separate responsabilities between rendering extensions.

2021-12-14 13:20 UTC, TataneCode commented
> As said in the original issue (#234), it's better to update the hyperlink object in order to be able to apply hyperlink on many objects instead only Image. Please update the Hyperlink object instead Image object. The goal is to separate responsabilities between rendering extensions.

I had that idea at first. But it does not match to the OpenXML doc structure. The link is embedded at several levels of a picture.
In the case of a text hyperlink, the label is embedded in the hyperlink (the contrary of the picture). Are you sure it is a good solution, not to conform the openxml structure ?

2021-12-15 07:51 UTC, TataneCode commented
Can you please review the new commit ?

2021-12-15 09:02 UTC, Alteoris requested changes

2021-12-15 09:07 UTC, Alteoris approved these changes

2022-02-14 08:06 UTC, closed without merging